#!/bin/bash
#Function to query and display

check_subdomain() {
	subdomain=$1
	domain=$2
	dig_output=$(dig ${subdomain}.${domain} | grep -A1 'ANSWER SECTION')
	record_type=$(echo "$dig_output" | awk '{print $4}')
	destination=$(echo "$dig_output" | awk '{print $5}')
	echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain=$1
subdomains=('www' 'lb-01' 'web-01' 'web-02')

if [ $# -eq 1 ]; then
	for subdomain in "${subdomains[@]}"; do
		check_subdomain $subdomain $domain
	done
elif [ $# -eq 2 ]; then
	subdomain=$2
	check_subdomain $subdomain $domain
else
	exit 1
fi
