#!/usr/bin/env bash
# This script Configure your Nginx server so that /redirect_me is redirecting to another page.

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo bash -c 'cat > /etc/nginx/sites-available/default' << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name desoyedami.tech;

    location = / {
        return 200 'Hello World!\n';
        add_header Content-Type text/plain;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF

# Restart Nginx to apply the new configuration
echo "Restarting Nginx..."
sudo service nginx restart

# Check Nginx status
echo "Checking Nginx status..."
sudo service nginx status
"4-not_found_page_404" 38L, 969C                                                                                                                                              15,15         All
