#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sed -i '/server_name _;/a \\n    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        root /var/www/html;\n    }' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

