#!/usr/bin/env bash
# This script Configure your Nginx server

# Update package list
apt-get update

# Install Nginx
apt-get install -y nginx

sudo bash -c 'cat > /etc/nginx/sites-available/default' << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name desoyedami.tech;

    location = / {
        return 200 'Hello World!\n';
        add_header Content-Type text/plain;
        add_header X-Served-By $hostname;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF

# Restart Nginx to apply the new configuration
echo "Restarting Nginx..."
sudo service nginx restart

# Check Nginx status
echo "Checking Nginx status..."
sudo service nginx status
