#!/usr/bin/env bash
#Install and configure HAproxy

#Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

#Configure HAproxy
cat <<EOF >> /etc/haproxy/haproxy.cfg
frontend my_frontend
        bind *:80
        default_backend my_backend

backend my_backend
        balance roundrobin
        server 503074-web-01 52.87.216.220:80
        server 503074-web-02 100.26.154.39:80
EOF

# Restart HAProxy service to apply
sudo service haproxy start
~                              
