#!/usr/bin/env bash
#Install and configure HAproxy

#Install HAproxy
apt-get update
apt-get install -y haproxy

#Configure HAproxy
cat <<EOF >> /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    mode http
    timeout client 10s
    timeout connect 5s
    timeout server 10s
    timeout http-request 10s

frontend my_frontend
    bind *:80
    default_backend my_backend

backend my_backend
    server 503074-web-01 52.87.216.220
    server 503074-web-02 100.26.154.39
EOF


# Restart HAproxy service to apply changes
service haproxy restart

# Enable HAproxy to start on boot
update-rc.d haproxy defaults

# Confirm HAproxy status
service haproxy status
