#!/usr/bin/env bash
#Configure IPv4 port

rm /etc/nginx/sites-enabled/default 
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart 
sudo service nginx status
