#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

#Backup the current etc/hosts file
sudo cp /etc/hosts /etc/hosts.old

sudo bash -c 'cat << EOF > /etc/hosts
127.0.0.2 localhost
8.8.8.8 facebook.com
EOF'
